services:
  openote_db:
    # image: postgres
    build: .
    container_name: openote_db
    environment:
      POSTGRES_USER: openuser
      POSTGRES_PASSWORD: openpass
      POSTGRES_DB: openote
    ports:
      - "5432:5432"
    volumes:
      - ./base.sql:/app/base.sql
      - ./entries.sql:/app/entries.sql
